# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.os }} Python ${{ matrix.python-version }} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: ['3.7', '3.8', '3.9']

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python ${{ matrix.os }} ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        pip install -r dev-requirements.txt
        python setup.py install
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Test with pytest
      run: python setup.py test

  build_aarch64:
    name: Build on aarch64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyver: [cp37-cp37m, cp38-cp38, cp39-cp39]
      fail-fast: false
    env:
      py: /opt/python/${{ matrix.pyver }}/bin/python
      img: quay.io/pypa/manylinux2014_aarch64

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1

    - name: Test on aarch64
      run: |
        docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
          ${{ env.img }} \
          bash -exc '${{ env.py }} -m venv .env && \
          source .env/bin/activate && \
          echo -e "\e[1;34m Install dependencies \e[0m" && \
          python -m pip install --upgrade pip && \
          python -m pip install flake8 pytest && \
          pip install -r dev-requirements.txt && \
          python setup.py install && \
          echo -e "\e[1;34m Lint with flake8 \e[0m" && \
          pip list && \
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics && \
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics && \
          echo -e "\e[1;34m Test with pytest \e[0m" && \
          python setup.py test && \
          deactivate'
